### ISSUE TITLE
Make possible to use models in pydeeplearn to be online

### ISSUE THREAD

**Issue by snurkabill** [mihaelacr/pydeeplearn#15]
It would be nice if neural network could be used for online training (ok ptretraining should be offline or none pretraining at all (as there is another issue)). This could aim for temporal difference learning techniques, when neural network needs to be online  (there is no offline version of it)

**Comment by snurkabill** [comment]
possible solution would be adding onlineTrain method which will cal ffineTune method wtih 1 epoch.

**Comment by mihaelacr** [comment]
I currently have no plans to implement online learning for pydeeplearn, but feel free to send a PR if you want to implement it and I will have a look.

**Comment by snurkabill** [comment]
well... :) I've started learning theano for this purpose. I am going to use your library in my comming thesis, I really need to get into python and theano, but there is no time.
